#!/bin/bash

GIT='/usr/local/bin/git'
PHP='/usr/bin/php'
GREP='/usr/bin/egrep'
PHP_FILES='.*(\.inc|\.php)$'

DIR=`dirname $0`
if [ -e $DIR/config ]; then
    source $DIR/config
fi

$GIT rev-parse --verify HEAD 2> /dev/null
if [ $? -eq 0 ]; then
  PREVCOMMIT='HEAD';
else
  PREVCOMMIT='4b825dc642cb6eb9a060e54bf8d69288fbee4904';
fi

CHANGED=`$GIT diff-index --diff-filter=ACMR --cached --name-only $PREVCOMMIT | $GREP "$PHP_FILES"`

STATUS=0
for FILE in $CHANGED; do
  MSG=`$PHP -dshort_open_tag=0 -n -l $FILE`
  if [ $? -ne 0 ]; then
    STATUS=1
    ERRORS+=$MSG
  fi 
done
if [ $STATUS -ne 0 ]; then
  echo -e "\n*****************************" 1>&2 
  echo "PHP errors detected in files:" 1>&2
  echo -e "$ERRORS"                    1>&2
  echo -e "\n*****************************" 1>&2 
fi
exit $STATUS
